import { Icon } from "../../components/ui/Icon";
import { getPhaseStatus } from "../../core/phases/phaseEngine";

export function RulesView({ state, onNavigate }) {
  const phase = getPhaseStatus(state.profile.phases);
  return <div className="page"><header className="page-header"><div className="eyebrow">RIKTNING FÖRE FART</div><h1>Systemkarta</h1><p>Faser och underhållsregler är referenser — de loggar inget och styr inte dina val åt dig.</p></header>
    {phase && <section className="card phase-panel"><div className="row-between"><div><span className="eyebrow">AKTUELL FAS</span><h2>{phase.name}</h2></div><strong>{phase.state === "current" ? `DAG ${phase.day}` : phase.percent === 100 ? "KLAR" : `OM ${phase.daysUntil} D`}</strong></div><p>{phase.description || phase.label}</p><div className="phase-track"><i style={{ width: `${phase.percent}%` }} /></div><div className="row-between"><small>{phase.startDate}</small><small>{phase.endDate}</small></div></section>}
    {state.profile.schedule?.length > 0 && <section className="section"><div className="section-title"><span>DYGNSSYSTEM</span><small>{state.profile.schedule.length} ankare</small></div><div className="card schedule-list">{state.profile.schedule.map((item, index) => <article key={`${item.time}-${index}`}><time>{item.time}{item.endTime !== item.time ? `–${item.endTime}` : ""}</time><div><strong>{item.label}</strong><small>{item.detail}</small></div></article>)}</div></section>}
    {state.profile.weeklyRoutine?.length > 0 && <section className="section"><div className="section-title"><span>VECKORUTIN</span><small>flexibel struktur</small></div><div className="week-system-grid">{state.profile.weeklyRoutine.map((item) => <article className="card" key={item.day}><span>{item.day.slice(0, 3).toUpperCase()}</span><strong>{item.study}</strong><small>{item.training}</small></article>)}</div></section>}
    {(state.profile.anchors?.morning?.length > 0 || state.profile.anchors?.evening?.length > 0) && <section className="section"><div className="section-title"><span>ANKARE & VERKTYG</span></div><div className="anchor-grid"><article className="card"><span className="eyebrow">MORGON · 10 MIN</span>{state.profile.anchors.morning.map((item) => <p key={item}>→ {item}</p>)}</article><article className="card"><span className="eyebrow">KVÄLL · 10–15 MIN</span>{state.profile.anchors.evening.map((item) => <p key={item}>→ {item}</p>)}</article></div>{state.profile.productivity && <aside className="card productivity-card"><Icon name="check" /><div><strong>{state.profile.productivity.taskSystem} = enda tasklistan</strong><p>{state.profile.productivity.taskRule} {state.profile.productivity.calendarSystem} används bara för fasta ankare.</p></div></aside>}</section>}
    <section className="section"><div className="section-title"><span>10 UNDERHÅLLSREGLER</span><small>{state.referenceRules.length} sparade</small></div><div className="rules-list">{state.referenceRules.map((rule, index) => <article className="card rule-row" key={rule.id}><span>{String(index + 1).padStart(2, "0")}</span><div><strong>{rule.title}</strong><p>{rule.detail}</p>{rule.moduleIds?.length > 0 && <div>{rule.moduleIds.map((moduleId) => <button key={moduleId} onClick={() => onNavigate(moduleId)}>{moduleId} <b>→</b></button>)}</div>}</div></article>)}</div>{!state.referenceRules.length && <div className="empty-state alive"><Icon name="shield" size={28} /><strong>Inga regler definierade.</strong><span>Den publika appen börjar tom. Regler kan läggas in via en seed eller JSON-backup utan att hårdkodas i gränssnittet.</span></div>}</section>
  </div>;
}
