import { localISO } from "../dates/dateUtils.js";

const now = () => new Date().toISOString();

export const GOAL_TEMPLATES = [
  { id: "savings", label: "Spara pengar", moduleId: "economy", source: "economy_total", type: "number", direction: "increase", unit: "kr", color: "#3ddc84", icon: "wallet" },
  { id: "weight", label: "Kroppsvikt", moduleId: "personal", source: "manual", type: "number", direction: "decrease", unit: "kg", color: "#a78bfa", icon: "trend" },
  { id: "nutrition", label: "Nutrition", moduleId: "nutrition", source: "manual", type: "number", direction: "decrease", unit: "kg", color: "#f472b6", icon: "nutrition" },
  { id: "reading", label: "Läsning", moduleId: "personal", source: "manual", type: "number", direction: "increase", unit: "böcker", color: "#5eb1ff", icon: "book" },
  { id: "study", label: "Studietid", moduleId: "studies", source: "study_weekly", type: "number", direction: "increase", unit: "h/vecka", color: "#5eb1ff", icon: "clock" },
  { id: "habit", label: "Ny vana", moduleId: "habits", source: "manual", type: "streak", direction: "increase", unit: "dagar", color: "#f0b429", icon: "flame" },
  { id: "project", label: "Projekt", moduleId: "personal", source: "manual", type: "checklist", direction: "increase", unit: "", color: "#3ddc84", icon: "target" },
  { id: "custom", label: "Eget mål", moduleId: "personal", source: "manual", type: "number", direction: "increase", unit: "", color: "#3ddc84", icon: "target" },
];

export const createInitialState = () => ({
  schemaVersion: 6,
  profile: {
    displayName: "",
    locale: "sv-SE",
    weekStartsOn: 1,
    coachMode: "direct",
    onboardingComplete: false,
    theme: "dark",
    quietIndicatorsEnabled: true,
    density: "comfortable",
    textScale: "normal",
    highContrast: false,
    localLockEnabled: false,
    gestures: { swipeRight: "complete", swipeLeft: "skip", doubleTap: "complete" },
    phases: [],
    schedule: [],
    anchors: { morning: [], evening: [] },
    kpis: [],
  },
  goals: {},
  goalEntries: {},
  goalTemplates: [],
  today: { completions: {}, dismissed: {}, contingency: null },
  dashboard: {
    pinnedGoalIds: [],
    hiddenWidgetIds: [],
    widgetOrder: ["economy", "habits", "gym", "studies", "nutrition", "reviews"],
    quickNavIds: ["system", "nutrition", "economy", "gym", "habits", "studies", "sleep"],
    widgetSizes: {},
    savedViews: [],
    activeSavedViewId: "",
  },
  modules: {
    economy: {
      accounts: {
        cash: { id: "cash", name: "Kontanter", kind: "spending", openingBalance: 0, color: "#3ddc84", archived: false },
        buffer: { id: "buffer", name: "Buffert", kind: "buffer", openingBalance: 0, color: "#f0b429", archived: false },
        savings: { id: "savings", name: "Högränta", kind: "savings", openingBalance: 0, color: "#5eb1ff", archived: false },
      },
      transactions: [],
      milestones: [],
      budgets: [],
      recurringTransactions: [],
      reconciliations: [],
      subscriptions: [],
    },
    gym: { workouts: [], workoutTemplates: [], exerciseCatalog: ["Bänkpress", "Knäböj", "Marklyft", "Axelpress", "Latsdrag"], exerciseAlternatives: {}, restTimerSeconds: 120, deloadEveryWeeks: 7 },
    habits: { habits: [], checkIns: [], routineGroups: [] },
    studies: { sessions: [], activeSession: null, roadmap: [], schedule: [], reviewQueue: [], timerMode: "free", pomodoroMinutes: 25 },
    reviews: { entries: [], templates: {} },
    nutrition: { calculations: [], latestCalculationId: null, profile: {}, mealLibrary: [], intakeLogs: [], supplementLibrary: [], foods: [], recipes: [], mealPlans: [], shoppingItems: [], pantryItems: [], hydrationLogs: [], dayTypes: {}, completedDays: {} },
    sleep: { logs: [], targetBedtime: "", targetWakeTime: "" },
    personal: {
      measurements: [],
    },
  },
  contingency: {
    definitions: [
      { id: "sick", label: "Sjuk", detail: "Skydda återhämtningen och gör bara det som hjälper kroppen." },
      { id: "travel", label: "Resa", detail: "Behåll ankaret, släpp den vanliga strukturen för idag." },
      { id: "low_motivation", label: "Låg motivation", detail: "Gör floor-versionen och bygg momentum utan att förhandla." },
      { id: "busy_week", label: "Intensiv vecka", detail: "Miniminivå är planen. Allt extra är bonus." },
    ],
    history: [],
  },
  planner: {
    events: [],
    inbox: [],
    wellbeing: [],
    maintenanceModes: [],
  },
  projects: [],
  lifeAdmin: {
    documents: [],
    decisions: [],
  },
  scenarios: [],
  coach: {
    rules: [
      { id: "protein_remaining", label: "Protein kvar idag", enabled: true, threshold: 20 },
      { id: "two_miss", label: "Rutiner som riskerar en andra miss", enabled: true, threshold: 1 },
      { id: "study_gap", label: "Studietid efter veckomålet", enabled: true, threshold: 1 },
      { id: "gym_plateau", label: "Träningsveckor utan progression", enabled: true, threshold: 3 },
      { id: "savings_deadline", label: "Sparkrav för deadline", enabled: true, threshold: 1 },
      { id: "recovery", label: "Sömn och tung träning", enabled: true, threshold: 6 },
    ],
  },
  automations: {
    rules: [
      { id: "gym_habit", label: "Gympass → träningsrutin full", enabled: true },
      { id: "nutrition_floor", label: "Kostintag → nutrition floor", enabled: true },
      { id: "nutrition_full", label: "Hel kostdag → nutrition full", enabled: true },
      { id: "study_goal", label: "Deep work → studiemål", enabled: true },
      { id: "two_miss_floor", label: "Två missar → floor-uppgift", enabled: true },
      { id: "saving_goal", label: "Insättning → ekonomimål", enabled: true },
    ],
  },
  favorites: [],
  recentCaptures: [],
  trash: [],
  referenceRules: [],
  activity: [{
    id: "activity-welcome",
    kind: "system",
    title: "Livssystem startat",
    detail: "Skapa ditt första mål och gör planen till din.",
    occurredAt: now(),
  }],
  meta: {
    createdAt: now(),
    updatedAt: now(),
    revision: 1,
    deviceId: "",
    lastSyncedAt: null,
    lastOpenedDate: localISO(),
  },
});
