import { useMemo, useState } from "react";
import { Icon } from "../../components/ui/Icon";
import { localISO } from "../../core/dates/dateUtils";
import { nutritionTargets, recipeTotals, weeklyNutritionAverage } from "./nutritionModel";

const id = (prefix) => `${prefix}-${crypto.randomUUID()}`;
const macros = ["calories", "protein", "carbs", "fat", "fiber"];
const blankIngredient = () => ({ id: id("ingredient"), foodId: "", grams: 100 });
const blankRecipe = () => ({ id: null, name: "", portions: 4, ingredients: [blankIngredient()] });

export function NutritionStudio({ state, onMutate, onLogRecipe }) {
  const nutrition = state.modules.nutrition;
  const [food, setFood] = useState({ name: "", calories: "", protein: "", carbs: "", fat: "", fiber: "" });
  const [recipe, setRecipe] = useState(blankRecipe);
  const [plan, setPlan] = useState({ date: localISO(), recipeId: "", portions: 1, dayType: "training" });
  const [shopping, setShopping] = useState("");
  const [pantry, setPantry] = useState({ name: "", quantity: 1, lowAt: 1 });
  const averages = useMemo(() => weeklyNutritionAverage(nutrition.intakeLogs), [nutrition.intakeLogs]);
  const targets = nutritionTargets(nutrition);
  const weights = state.modules.personal.measurements.filter((item) => item.type === "weight").slice(-8);
  const addFood = () => {
    if (!food.name.trim()) return;
    const item = { id: id("food"), name: food.name.trim(), ...Object.fromEntries(macros.map((key) => [key, Number(food[key]) || 0])), favorite: false, createdAt: new Date().toISOString() };
    onMutate((current) => ({ ...current, modules: { ...current.modules, nutrition: { ...current.modules.nutrition, foods: [...current.modules.nutrition.foods, item] } } }), `Livsmedel sparat: ${item.name}`, "Näringsvärden per 100 g");
    setFood({ name: "", calories: "", protein: "", carbs: "", fat: "", fiber: "" });
  };
  const addRecipe = () => {
    const ingredients = recipe.ingredients.map((ingredient) => {
      const source = nutrition.foods.find((item) => item.id === ingredient.foodId);
      return source ? { ...ingredient, name: source.name, grams: Number(ingredient.grams) || 0 } : null;
    }).filter((ingredient) => ingredient && ingredient.grams > 0);
    if (!recipe.name.trim() || !ingredients.length) return;
    const existing = nutrition.recipes.find((item) => item.id === recipe.id);
    const item = { ...(existing || {}), id: existing?.id || id("recipe"), name: recipe.name.trim(), portions: Number(recipe.portions) || 1, ingredients, favorite: existing?.favorite || false, createdAt: existing?.createdAt || new Date().toISOString(), updatedAt: new Date().toISOString() };
    onMutate((current) => ({ ...current, modules: { ...current.modules, nutrition: { ...current.modules.nutrition, recipes: existing ? current.modules.nutrition.recipes.map((entry) => entry.id === item.id ? item : entry) : [...current.modules.nutrition.recipes, item] } } }), `${existing ? "Recept uppdaterat" : "Recept sparat"}: ${item.name}`, `${item.portions} portioner · ${ingredients.length} ingredienser`);
    setRecipe(blankRecipe());
  };
  const editRecipe = (item) => setRecipe({ id: item.id, name: item.name, portions: item.portions, ingredients: item.ingredients.map((ingredient) => ({ ...ingredient })) });
  const deleteRecipe = (item) => onMutate((current) => ({ ...current, modules: { ...current.modules, nutrition: { ...current.modules.nutrition, recipes: current.modules.nutrition.recipes.filter((entry) => entry.id !== item.id), mealPlans: current.modules.nutrition.mealPlans.filter((entry) => entry.recipeId !== item.id) } } }), `Recept raderat: ${item.name}`, "Du kan ångra direkt");
  const addPlan = () => {
    const source = nutrition.recipes.find((item) => item.id === plan.recipeId);
    if (!source) return;
    const item = { id: id("meal-plan"), ...plan, portions: Number(plan.portions) || 1, name: source.name, createdAt: new Date().toISOString() };
    const ingredients = source.ingredients.map((ingredient) => ({ id: id("shopping"), name: ingredient.name, quantity: `${Math.round(ingredient.grams * item.portions)} g`, category: "Mat", checked: false, sourceId: item.id }));
    onMutate((current) => ({ ...current, modules: { ...current.modules, nutrition: { ...current.modules.nutrition, mealPlans: [...current.modules.nutrition.mealPlans, item], shoppingItems: [...current.modules.nutrition.shoppingItems, ...ingredients], dayTypes: { ...current.modules.nutrition.dayTypes, [item.date]: item.dayType } } } }), `Måltid planerad: ${item.name}`, `${item.date} · ${item.dayType === "training" ? "träningsdag" : "vilodag"}`);
  };
  return <div className="nutrition-studio">
    <section className="nutrition-week card"><div><span className="eyebrow">7-DAGARSSNITT · {averages.loggedDays}/7 LOGGADE</span><strong>{averages.calories.toLocaleString("sv-SE")} <small>kcal</small></strong><p>{targets.calories ? `${Math.round(averages.calories - targets.calories)} kcal mot dagsmålet` : "Sätt ett mål i kalkylatorn"}</p></div><div className="weekly-macros"><span><b>{averages.protein}</b> g protein</span><span><b>{averages.carbs}</b> g kolhydrater</span><span><b>{averages.fat}</b> g fett</span></div>{weights.length >= 2 && <div className="weight-correlation"><Icon name="chart" /><span>Vikttrend</span><strong>{Number(weights.at(-1).value) - Number(weights[0].value) > 0 ? "+" : ""}{(Number(weights.at(-1).value) - Number(weights[0].value)).toFixed(1)} kg</strong><small>över {weights.length} mätningar</small></div>}<div className="day-targets"><label>Träningsdag kcal<input type="number" value={nutrition.profile.trainingDayCalories || targets.calories || ""} onChange={(event) => onMutate((current) => ({ ...current, modules: { ...current.modules, nutrition: { ...current.modules.nutrition, profile: { ...current.modules.nutrition.profile, trainingDayCalories: Number(event.target.value) } } } }), "Kalorimål träningsdag", event.target.value)} /></label><label>Vilodag kcal<input type="number" value={nutrition.profile.restDayCalories || targets.calories || ""} onChange={(event) => onMutate((current) => ({ ...current, modules: { ...current.modules, nutrition: { ...current.modules.nutrition, profile: { ...current.modules.nutrition.profile, restDayCalories: Number(event.target.value) } } } }), "Kalorimål vilodag", event.target.value)} /></label></div></section>

    <div className="nutrition-studio-grid"><section className="card studio-editor"><div className="section-title"><span>EGNA LIVSMEDEL</span><small>per 100 g</small></div><input value={food.name} onChange={(event) => setFood({ ...food, name: event.target.value })} placeholder="Livsmedel" /><div className="macro-input-grid">{macros.map((key) => <label key={key}>{key === "calories" ? "kcal" : key}<input type="number" min="0" step="0.1" value={food[key]} onChange={(event) => setFood({ ...food, [key]: event.target.value })} /></label>)}</div><button className="secondary-button" onClick={addFood}>Spara livsmedel</button><div className="food-library">{nutrition.foods.map((item) => <article key={item.id}><div><strong>{item.name}</strong><small>{item.calories} kcal · P {item.protein} · K {item.carbs} · F {item.fat}</small></div><button aria-label={`Favoritmarkera ${item.name}`} onClick={() => onMutate((current) => ({ ...current, modules: { ...current.modules, nutrition: { ...current.modules.nutrition, foods: current.modules.nutrition.foods.map((entry) => entry.id === item.id ? { ...entry, favorite: !entry.favorite } : entry) } } }), "Livsmedelsfavorit uppdaterad", item.name)}>{item.favorite ? "★" : "☆"}</button></article>)}</div></section>

      <section className="card studio-editor"><div className="section-title"><span>RECEPT & PORTIONER</span><small>{recipe.id ? "redigerar" : `${recipe.ingredients.length} ingredienser`}</small></div><input value={recipe.name} onChange={(event) => setRecipe({ ...recipe, name: event.target.value })} placeholder="Receptnamn" /><div className="recipe-ingredient-editor">{recipe.ingredients.map((ingredient, index) => <div className="field-grid recipe-ingredient-row" key={ingredient.id}><select aria-label={`Ingrediens ${index + 1}`} value={ingredient.foodId} onChange={(event) => setRecipe({ ...recipe, ingredients: recipe.ingredients.map((item) => item.id === ingredient.id ? { ...item, foodId: event.target.value } : item) })}><option value="">Välj ingrediens</option>{nutrition.foods.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select><input aria-label={`Gram ingrediens ${index + 1}`} type="number" min="1" value={ingredient.grams} onChange={(event) => setRecipe({ ...recipe, ingredients: recipe.ingredients.map((item) => item.id === ingredient.id ? { ...item, grams: event.target.value } : item) })} placeholder="gram" />{recipe.ingredients.length > 1 && <button className="micro-danger" aria-label={`Ta bort ingrediens ${index + 1}`} onClick={() => setRecipe({ ...recipe, ingredients: recipe.ingredients.filter((item) => item.id !== ingredient.id) })}><Icon name="trash" size={14} /></button>}</div>)}</div><button className="text-button" onClick={() => setRecipe({ ...recipe, ingredients: [...recipe.ingredients, blankIngredient()] })}><Icon name="plus" size={14} /> Lägg till ingrediens</button><label>Portioner<input type="number" min="1" value={recipe.portions} onChange={(event) => setRecipe({ ...recipe, portions: event.target.value })} /></label><div className="row-actions"><button className="secondary-button" onClick={addRecipe}>{recipe.id ? "Spara ändringar" : "Skapa recept"}</button>{recipe.id && <button onClick={() => setRecipe(blankRecipe())}>Avbryt</button>}</div><div className="recipe-library">{nutrition.recipes.map((item) => { const total = recipeTotals(item, nutrition.foods); return <article key={item.id}><div><strong>{item.name}</strong><small>{item.ingredients.length} ingredienser · per portion · {total.calories} kcal · {total.protein} g protein</small></div><div className="row-actions"><button onClick={() => onLogRecipe(item, total, 1)}>Logga</button><button onClick={() => onLogRecipe(item, total, 1.5)}>1,5×</button><button onClick={() => onLogRecipe(item, total, 2)}>2×</button><button aria-label={`Redigera ${item.name}`} onClick={() => editRecipe(item)}><Icon name="edit" size={13} /></button><button aria-label={`Radera ${item.name}`} onClick={() => deleteRecipe(item)}><Icon name="trash" size={13} /></button></div></article>; })}</div></section>
    </div>

    <section className="card meal-planner"><div className="section-title"><span>MÅLTIDSPLAN & AUTOMATISK INKÖPSLISTA</span></div><div className="field-grid four"><label>Datum<input type="date" value={plan.date} onChange={(event) => setPlan({ ...plan, date: event.target.value })} /></label><label>Recept<select value={plan.recipeId} onChange={(event) => setPlan({ ...plan, recipeId: event.target.value })}><option value="">Välj</option>{nutrition.recipes.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Portioner<input type="number" min=".5" step=".5" value={plan.portions} onChange={(event) => setPlan({ ...plan, portions: event.target.value })} /></label><label>Dagstyp<select value={plan.dayType} onChange={(event) => setPlan({ ...plan, dayType: event.target.value })}><option value="training">Träningsdag</option><option value="rest">Vilodag</option></select></label></div><button className="secondary-button" onClick={addPlan}>Planera + lägg ingredienser i listan</button><div className="meal-plan-strip">{nutrition.mealPlans.slice().sort((a, b) => a.date.localeCompare(b.date)).map((item) => <article key={item.id}><span>{item.date.slice(5)}</span><strong>{item.name}</strong><small>{item.portions}× · {item.dayType === "training" ? "träning" : "vila"}</small></article>)}</div></section>

    <div className="nutrition-studio-grid"><section className="card studio-editor"><div className="section-title"><span>INKÖPSLISTA</span></div><div className="inline-create"><input value={shopping} onChange={(event) => setShopping(event.target.value)} placeholder="Lägg till vara" /><button onClick={() => { if (!shopping.trim()) return; const item = { id: id("shopping"), name: shopping.trim(), quantity: "", category: "Övrigt", checked: false }; onMutate((current) => ({ ...current, modules: { ...current.modules, nutrition: { ...current.modules.nutrition, shoppingItems: [...current.modules.nutrition.shoppingItems, item] } } }), `Inköp: ${item.name}`, "Tillagt i listan"); setShopping(""); }}><Icon name="plus" size={15} /></button></div><div className="check-list">{nutrition.shoppingItems.map((item) => <label key={item.id}><input type="checkbox" checked={item.checked} onChange={() => onMutate((current) => ({ ...current, modules: { ...current.modules, nutrition: { ...current.modules.nutrition, shoppingItems: current.modules.nutrition.shoppingItems.map((entry) => entry.id === item.id ? { ...entry, checked: !entry.checked } : entry) } } }), "Inköpslista uppdaterad", item.name)} /><span>{item.name}</span><small>{item.quantity}</small></label>)}</div></section>
      <section className="card studio-editor"><div className="section-title"><span>SKAFFERI & LAGER</span></div><input value={pantry.name} onChange={(event) => setPantry({ ...pantry, name: event.target.value })} placeholder="Proteinpulver, kreatin…" /><div className="field-grid"><label>Antal<input type="number" min="0" value={pantry.quantity} onChange={(event) => setPantry({ ...pantry, quantity: Number(event.target.value) })} /></label><label>Varna vid<input type="number" min="0" value={pantry.lowAt} onChange={(event) => setPantry({ ...pantry, lowAt: Number(event.target.value) })} /></label></div><button className="secondary-button" onClick={() => { if (!pantry.name.trim()) return; const item = { ...pantry, id: id("pantry") }; onMutate((current) => ({ ...current, modules: { ...current.modules, nutrition: { ...current.modules.nutrition, pantryItems: [...current.modules.nutrition.pantryItems, item] } } }), `Lagerartikel: ${item.name}`, `${item.quantity} i lager`); setPantry({ name: "", quantity: 1, lowAt: 1 }); }}>Lägg till lagerartikel</button><div className="mini-list">{nutrition.pantryItems.map((item) => <div className={Number(item.quantity) <= Number(item.lowAt) ? "low-stock" : ""} key={item.id}><strong>{item.name}</strong><small>{item.quantity} kvar{Number(item.quantity) <= Number(item.lowAt) ? " · lågt lager" : ""}</small><button onClick={() => onMutate((current) => ({ ...current, modules: { ...current.modules, nutrition: { ...current.modules.nutrition, shoppingItems: [...current.modules.nutrition.shoppingItems, { id: id("shopping"), name: item.name, quantity: "", category: "Lager", checked: false }] } } }), `Inköp: ${item.name}`, "Lågt lager")}>Köp</button></div>)}</div></section>
    </div>

    <section className="hydration-bar card"><div><Icon name="pulse" /><span><strong>Vätska, koffein & kreatin</strong><small>Snabblogga utan att skapa en hel måltid.</small></span></div>{[["water", "Vatten 500 ml", 500], ["caffeine", "Koffein 100 mg", 100], ["creatine", "Kreatin 5 g", 5]].map(([kind, label, amount]) => <button key={kind} onClick={() => onMutate((current) => ({ ...current, modules: { ...current.modules, nutrition: { ...current.modules.nutrition, hydrationLogs: [...current.modules.nutrition.hydrationLogs, { id: id("hydration"), kind, amount, date: localISO(), createdAt: new Date().toISOString() }] } } }), label, "Loggat")}>+ {label}</button>)}</section>
  </div>;
}
