import { useEffect, useMemo, useState } from "react";
import { Icon } from "../../components/ui/Icon";
import { addDays } from "../../core/system/systemEngine";
import { isThisWeek, localISO } from "../../core/dates/dateUtils";

const clock = (seconds) => `${String(Math.floor(seconds / 3600)).padStart(2, "0")}:${String(Math.floor(seconds % 3600 / 60)).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`;
const id = (prefix) => `${prefix}-${crypto.randomUUID()}`;

export function StudiesView({ data, onStart, onStop, onPause, onToggleRoadmap, onAddRoadmap, onRemoveRoadmap, onMutate }) {
  const [sessionForm, setSessionForm] = useState({ subject: "", project: "", mode: data.timerMode || "free", pomodoroMinutes: data.pomodoroMinutes || 25 });
  const [roadmapForm, setRoadmapForm] = useState({ name: "", resource: "", examDate: "", dependsOn: "" });
  const [schedule, setSchedule] = useState({ subject: "", date: localISO(), start: "08:00", plannedMinutes: 90 });
  const [review, setReview] = useState({ topic: "", dueDate: localISO(), intervalDays: 3 });
  const [now, setNow] = useState(() => Date.now());
  useEffect(() => {
    if (!data.activeSession) return undefined;
    const timer = window.setInterval(() => setNow(Date.now()), 1000);
    return () => window.clearInterval(timer);
  }, [data.activeSession]);
  const pausedCurrent = data.activeSession?.pausedAt ? now - new Date(data.activeSession.pausedAt).getTime() : 0;
  const elapsed = data.activeSession ? Math.max(0, Math.floor((now - new Date(data.activeSession.startedAt).getTime() - Number(data.activeSession.totalPausedMs || 0) - pausedCurrent) / 1000)) : 0;
  const weekly = data.sessions.filter((session) => isThisWeek(session.startedAt));
  const minutes = weekly.reduce((sum, session) => sum + Number(session.durationMinutes || 0), 0);
  const days = [1, 2, 3, 4, 5, 6, 0].map((day) => weekly.filter((session) => new Date(session.startedAt).getDay() === day).reduce((sum, session) => sum + Number(session.durationMinutes || 0), 0));
  const max = Math.max(60, ...days);
  const roadmap = data.roadmap || [];
  const roadmapDone = roadmap.filter((item) => item.done).length;
  const latest = data.sessions.at(-1);
  const focusStats = useMemo(() => {
    if (!data.sessions.length) return null;
    const byDay = new Map(), byHour = new Map();
    data.sessions.forEach((session) => { const date = new Date(session.startedAt); byDay.set(date.getDay(), (byDay.get(date.getDay()) || 0) + Number(session.durationMinutes || 0)); byHour.set(date.getHours(), (byHour.get(date.getHours()) || 0) + Number(session.durationMinutes || 0)); });
    const best = (map) => [...map.entries()].sort((a, b) => b[1] - a[1])[0]?.[0];
    return { day: ["söndag", "måndag", "tisdag", "onsdag", "torsdag", "fredag", "lördag"][best(byDay)], hour: best(byHour) };
  }, [data.sessions]);
  const start = (override = {}) => {
    const next = { ...sessionForm, ...override };
    if (!next.subject.trim()) return;
    onStart(next);
    setSessionForm((current) => ({ ...current, subject: "", project: "" }));
  };
  const addSchedule = () => {
    if (!schedule.subject.trim()) return;
    const item = { ...schedule, id: id("study-plan"), plannedMinutes: Number(schedule.plannedMinutes), status: "planned" };
    onMutate((current) => ({ ...current, modules: { ...current.modules, studies: { ...current.modules.studies, schedule: [...current.modules.studies.schedule, item] } } }), `Studieblock planerat: ${item.subject}`, `${item.date} · ${item.start}`);
    setSchedule({ ...schedule, subject: "" });
  };

  return <div className="page">
    <header className="page-header"><div className="eyebrow">DEEP WORK</div><h1>Studier</h1><p>Planera, fokusera, pausa när det behövs och repetera vid rätt tid.</p></header>
    {data.blocks?.length > 0 && <section className="study-blocks">{data.blocks.map((block) => <article className="card" key={block.start}><span>{block.start}–{block.end}</span><strong>{block.label}</strong></article>)}<p>{data.noteStyle}</p></section>}
    <section className={`timer-card card ${data.activeSession ? "running" : ""} ${data.activeSession?.pausedAt ? "paused" : ""}`}><div className="timer-orbit"><Icon name="clock" size={30} /><strong>{clock(elapsed)}</strong><span>{data.activeSession?.pausedAt ? "PAUSAD" : data.activeSession?.subject || "REDO ATT FOKUSERA"}</span></div>{data.activeSession ? <div className="timer-running-actions"><button className="secondary-button" onClick={onPause}>{data.activeSession.pausedAt ? "Fortsätt" : "Pausa"}</button><button className="danger-button" onClick={() => onStop(elapsed)}>Avsluta och spara</button></div> : <div className="timer-start"><div className="field-grid"><input value={sessionForm.subject} onChange={(event) => setSessionForm({ ...sessionForm, subject: event.target.value })} placeholder="Vad ska du studera?" /><input value={sessionForm.project} onChange={(event) => setSessionForm({ ...sessionForm, project: event.target.value })} placeholder="Projekt · valfritt" /></div><div className="timer-mode-row"><div className="segmented"><button className={sessionForm.mode === "free" ? "active" : ""} onClick={() => setSessionForm({ ...sessionForm, mode: "free" })}>Fritt block</button><button className={sessionForm.mode === "pomodoro" ? "active" : ""} onClick={() => setSessionForm({ ...sessionForm, mode: "pomodoro" })}>Pomodoro</button></div>{sessionForm.mode === "pomodoro" && <select value={sessionForm.pomodoroMinutes} onChange={(event) => setSessionForm({ ...sessionForm, pomodoroMinutes: Number(event.target.value) })}><option value="25">25 min</option><option value="50">50 min</option><option value="90">90 min</option></select>}</div><button className="primary-button blue-button" onClick={() => start()}>Starta session</button>{latest && <button className="secondary-button" onClick={() => start({ subject: latest.subject, project: latest.project || "" })}>Fortsätt senaste: {latest.subject}</button>}</div>}</section>
    <section className="card weekly-card"><div className="row-between"><div><span className="eyebrow">DEN HÄR VECKAN</span><strong>{minutes < 60 ? minutes : (minutes / 60).toFixed(1)} <small>{minutes < 60 ? "minuter" : "timmar"}</small></strong></div><span className="positive mono">{weekly.length} BLOCK</span></div><div className="bar-chart">{days.map((value, index) => <div key={index}><i style={{ height: `${Math.max(4, value / max * 100)}%` }} /><span>{["M", "T", "O", "T", "F", "L", "S"][index]}</span></div>)}</div>{focusStats && <p className="focus-insight">Ditt historiskt starkaste fokusfönster är <strong>{focusStats.day} omkring {String(focusStats.hour).padStart(2, "0")}:00</strong>.</p>}</section>
    <section className="section"><div className="section-title"><span>VECKOSCHEMA · PLANERAT MOT FAKTISKT</span></div><article className="card study-scheduler"><div className="field-grid four"><input value={schedule.subject} onChange={(event) => setSchedule({ ...schedule, subject: event.target.value })} placeholder="Ämne" /><input type="date" value={schedule.date} onChange={(event) => setSchedule({ ...schedule, date: event.target.value })} /><input type="time" value={schedule.start} onChange={(event) => setSchedule({ ...schedule, start: event.target.value })} /><input type="number" min="15" step="15" value={schedule.plannedMinutes} onChange={(event) => setSchedule({ ...schedule, plannedMinutes: event.target.value })} /></div><button className="secondary-button" onClick={addSchedule}>Planera block</button><div className="study-plan-list">{data.schedule.map((item) => { const actual = data.sessions.filter((session) => localISO(new Date(session.startedAt)) === item.date && session.subject === item.subject).reduce((sum, session) => sum + Number(session.durationMinutes), 0); return <div key={item.id}><span><strong>{item.subject}</strong><small>{item.date} · {item.start}</small></span><b>{actual}/{item.plannedMinutes} min</b><div className="row-actions"><button onClick={() => onMutate((current) => ({ ...current, modules: { ...current.modules, studies: { ...current.modules.studies, schedule: current.modules.studies.schedule.map((entry) => entry.id === item.id ? { ...entry, date: addDays(entry.date, -1) } : entry) } } }), "Studieblock flyttat", "En dag bakåt")}>←</button><button onClick={() => onMutate((current) => ({ ...current, modules: { ...current.modules, studies: { ...current.modules.studies, schedule: current.modules.studies.schedule.map((entry) => entry.id === item.id ? { ...entry, date: addDays(entry.date, 1) } : entry) } } }), "Studieblock flyttat", "En dag framåt")}>→</button></div></div>; })}</div></article></section>
    <section className="section roadmap-section"><div className="section-title"><span>CERTIFIERINGSROADMAP</span><small>{roadmapDone}/{roadmap.length} klara</small></div><div className="card roadmap-card">{roadmap.length > 0 && <div className="roadmap-progress"><i style={{ width: `${roadmapDone / roadmap.length * 100}%` }} /></div>}<div className="roadmap-list">{roadmap.map((item) => { const blocked = item.dependsOn && !roadmap.find((candidate) => candidate.id === item.dependsOn)?.done; return <div className={`roadmap-row ${item.done ? "done" : ""} ${blocked ? "blocked" : ""}`} key={item.id}><button disabled={blocked} className="roadmap-check" onClick={() => onToggleRoadmap(item.id)}><Icon name="check" size={15} /></button><div><strong>{item.name}</strong><small>{blocked ? "Väntar på föregående steg" : item.resource || item.note || "Redo"}{item.examDate ? ` · tenta ${item.examDate}` : ""}</small></div><button className="roadmap-remove" onClick={() => onRemoveRoadmap(item.id)}><Icon name="close" size={14} /></button></div>; })}</div><div className="roadmap-editor"><input value={roadmapForm.name} onChange={(event) => setRoadmapForm({ ...roadmapForm, name: event.target.value })} placeholder="Certifiering eller steg" /><input value={roadmapForm.resource} onChange={(event) => setRoadmapForm({ ...roadmapForm, resource: event.target.value })} placeholder="Resurs eller länk" /><div className="field-grid"><input type="date" value={roadmapForm.examDate} onChange={(event) => setRoadmapForm({ ...roadmapForm, examDate: event.target.value })} /><select value={roadmapForm.dependsOn} onChange={(event) => setRoadmapForm({ ...roadmapForm, dependsOn: event.target.value })}><option value="">Inget beroende</option>{roadmap.map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></div><button className="secondary-button" onClick={() => { if (!roadmapForm.name.trim()) return; onAddRoadmap(roadmapForm); setRoadmapForm({ name: "", resource: "", examDate: "", dependsOn: "" }); }}><Icon name="plus" size={16} /> Lägg till steg</button></div></div></section>
    <section className="section"><div className="section-title"><span>REPETITIONSKÖ</span><small>{data.reviewQueue.filter((item) => item.dueDate <= localISO()).length} idag</small></div><article className="card review-queue"><div className="inline-create"><input value={review.topic} onChange={(event) => setReview({ ...review, topic: event.target.value })} placeholder="Vad ska repeteras?" /><input type="date" value={review.dueDate} onChange={(event) => setReview({ ...review, dueDate: event.target.value })} /><button onClick={() => { if (!review.topic.trim()) return; const item = { ...review, id: id("review-topic"), intervalDays: Number(review.intervalDays) }; onMutate((current) => ({ ...current, modules: { ...current.modules, studies: { ...current.modules.studies, reviewQueue: [...current.modules.studies.reviewQueue, item] } } }), `Repetition: ${item.topic}`, item.dueDate); setReview({ ...review, topic: "" }); }}><Icon name="plus" size={15} /></button></div>{data.reviewQueue.map((item) => <div className={item.dueDate <= localISO() ? "due" : ""} key={item.id}><span><strong>{item.topic}</strong><small>{item.dueDate <= localISO() ? "Bör repeteras idag" : `Nästa ${item.dueDate}`}</small></span><button onClick={() => onMutate((current) => ({ ...current, modules: { ...current.modules, studies: { ...current.modules.studies, reviewQueue: current.modules.studies.reviewQueue.map((entry) => entry.id === item.id ? { ...entry, dueDate: addDays(localISO(), entry.intervalDays || 3), intervalDays: Math.min(60, Math.ceil((entry.intervalDays || 3) * 1.8)) } : entry) } } }), `Repeterat: ${item.topic}`, "Intervallet ökades")}>Klar</button></div>)}</article></section>
    <section className="section"><div className="section-title"><span>SENASTE SESSIONER</span></div><div className="history-list">{data.sessions.slice().reverse().slice(0, 10).map((session) => <div className="history-row" key={session.id}><Icon name="book" size={17} /><div><strong>{session.subject}</strong><small>{session.project ? `${session.project} · ` : ""}{new Date(session.startedAt).toLocaleDateString("sv-SE")}</small></div><b className="mono">{session.durationMinutes} min</b></div>)}</div></section>
  </div>;
}
